spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/sampledb
    username: milodb
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
